### ISSUE TITLE
Running Clair without direct internet access

### ISSUE THREAD

**Issue by stengerh** [quay/clair#559] opened 2018-06-04 07:58 UTC
**Description of Problem**:
I have a project where Clair is run in a secured network where Clair has no direct access to the internet. So far the solution was to patch Clair to download the NVD files from an internal mirror. I would prefer to get rid of this patching process. Would you be willing to add a configuration option for the NVD server URL? Or is there a better way?

**Expected Outcome**:
Official Clair release can be run without direct internet access.

**Actual Outcome**:

**Environment**:
- Clair version/image: 2.0.1
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by jzelinskie** [comment] 2018-07-06 01:44
Duplicate of #401

**Closed as completed by jzelinskie** 2018-07-06 01:44 UTC
