### ISSUE TITLE
Permission Denied for clair_clair container

### ISSUE THREAD

**Issue by dharmit** [quay/clair#213] opened 2016-07-07 07:49 UTC
I'm following the Docker Compose section to get started with Clair but it's failing for me with below error in docker logs:

```
$ docker logs 6d9
2016-07-07 07:45:37.968998 C | main: failed to load configuration: open /config/config.yaml: permission denied
```

When I try to create a container from the image, it fails with below message:

```
$ docker run -it quay.io/coreos/clair ls
2016-07-07 07:46:53.216183 C | main: failed to load configuration: open /etc/clair/config.yaml: no such file or directory
```

An issue with the image maybe? But it's a 5 weeks old image so I doubt if that's the issue. 

Let me know if I need to provide additional info.

**Comment by Quentin-M** [comment] 2016-07-07 10:26
Hi.

I could not reproduce with the latest version of the README (which uses Clair v1.2.2).

Docker Compose mounts your local folder `./clair_config` into the container at `/config`. Could you please make sure that this local folder exists and that it has proper permissions?

**Comment by dharmit** [comment] 2016-07-07 12:59
Do these permissions suffice?

```
$ ls -ld clair_config
drwxrwxr-x. 2 dshah dshah 4096 Jul  7 12:24 clair_config

$ ls -l clair_config
total 4
-rw-rw-r--. 1 dshah dshah 2691 Jul  7 12:24 config.yaml
```

**Comment by davyboyhayes** [comment] 2016-10-24 13:00
@dharmit ... I had similar... I altered docker-compose.yml to change the volume:

./clair_config:/config

to

~/clair_config:/config

and recomposing the app, and it started nicely

**Comment by jzelinskie** [comment] 2017-05-24 22:47
closing due to age. please remake this issue if it's still relevant. thanks

**Closed as completed by jzelinskie** 2017-05-24 22:47 UTC
Labels: kind/question
