### ISSUE TITLE
Following Local Development steps, Clair container still showing in Init state in minikube after many hours

### ISSUE THREAD

**Issue by bbakersc** [quay/clair#914] opened 2020-02-05 13:21 UTC
### Description of Problem / Feature Request

I'm following the steps at [Local Development](https://github.com/quay/clair/blob/master/Documentation/local-development.md) and everything seems to be being built correctly, but when I check the status of the running container, it's still showing in the `Init` status even after running overnight. I know the documentation says the initial startup can take some time, but this seems a bit too long.

### Expected Outcome

A running container with the built Clair in it

### Actual Outcome

`
NAME                     READY   STATUS     RESTARTS   AGE  
clair-5cb6bb8f57-tnfnw   0/1     Init:0/1   0          12m  
`
(this is from this morning after re-doing everything)

### Environment

- Clair version/image: Version built from Makefile
- Clair client name/version: Version built from Makefile 
- Host OS: macOS Mojave 10.14.6
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.7.0
- Kubernetes version (use `kubectl version`): 1.17
- Helm version (use `helm version`): 2.16.1
- Network/Firewall setup: Running locally

**Comment by mattjnewberry** [comment] 2020-02-11 15:14
I'm having a similar issue, where the Init Container *pg-ready-wait* is not responding to the health check and therefore the container is stuck in a pending state. 

```
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
helm install --name clair-pg ./local-dev/helm/clair-pg
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
Makefile:40: recipe for target 'deploy-local' failed
make: [deploy-local] Error 1 (ignored)
helm delete --purge clair
release "clair" deleted
helm install --name clair ./local-dev/helm/clair
NAME:   clair
LAST DEPLOYED: Tue Feb 11 15:01:26 2020
NAMESPACE: default
STATUS: DEPLOYED
```
Perhaps is the issue? 

Running `kubectl logs ${YOUR_CLAIR_CONTAINER} -c pg-ready-wait` will give you the logs from the Init Container. Mine show no response from the db.

**Comment by jkhalilkayak** [comment] 2020-02-11 15:37
So far, I have no idea what the issue is.
I will keep looking trying to find out why is clair resolving to bad urls.

Will try to re-install it on a new machine and check results.

**Comment by jkhalilkayak** [comment] 2020-02-11 16:16
So NIST retired their XML feed as of Feb 10, 2020 and they rolled out a new
API.
https://nvd.nist.gov/General/News/New-NVD-CVE-CPE-API-and-SOAP-Retirement

Clair queries the CVEs using the XML format, I guess we have to wait
until a new version comes out.

**Comment by hdonnay** [comment] 2020-08-31 18:51
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!

**Closed as completed by hdonnay** 2020-08-31 18:51 UTC
