### ISSUE TITLE
Could not find layer

### ISSUE THREAD

**Issue by ccao93** [quay/clair#380] opened 2017-04-28 21:02 UTC
Hi,

I am using docker compose to run the containers and try to use **analyze-local-images** to analyze my local docker images but meet the problem of:
```
Could not analyze layer: Got response 400 with message {"Error":{"Message":"could not find layer"}}
```
My docker version is:
```
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
The logs from clair_clair is like the following:
```
2017-04-28 19:45:55.563552 E | clair: layer sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190: failed to extract data from /var/folders/l9/2s6prfn55695_31ynr7fs57wd4b4tv/T/analyze-local-image-512895501/sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190/layer.tar: could not find layer
2017-04-28 19:45:55.564165 I | v1: 172.19.0.1:56820 "POST /v1/layers" 400 (1.493015ms)
2017-04-28 20:25:02.181181 E | clair: layer sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190: failed to extract data from /tmp/analyze-local-image-456155647/sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190/layer.tar: could not find layer
2017-04-28 20:25:02.181575 I | v1: 172.19.0.1:57758 "POST /v1/layers" 400 (1.819525ms)
2017-04-28 20:36:54.972615 E | clair: layer sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190: failed to extract data from /var/folders/l9/2s6prfn55695_31ynr7fs57wd4b4tv/T/analyze-local-image-457579400/sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190/layer.tar: could not find layer
2017-04-28 20:36:54.973070 I | v1: 172.19.0.1:58046 "POST /v1/layers" 400 (1.391237ms)
2017-04-28 20:44:35.848070 E | clair: layer sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190: failed to extract data from /var/folders/l9/2s6prfn55695_31ynr7fs57wd4b4tv/T/analyze-local-image-811151104/sha256:6f4ea9f58e4e521f84992aab805661a1431cdbd625ddc7405161d31c76555190/layer.tar: could not find layer
2017-04-28 20:44:35.848482 I | v1: 172.19.0.1:58232 "POST /v1/layers" 400 (1.18758ms)
```
The $TMPDIR is: 
```
env | grep TMPDIR
TMPDIR=/var/folders/l9/2s6prfn55695_31ynr7fs57wd4b4tv/T/
```

Is there anybody know how to fix this problem? I have tried to change $TMPDIR=/tmp but it doens't work. 

Thank you.

**Comment by srkiNZ84** [comment] 2017-05-02 02:23
I believe your issue is a duplicate of: #372

Which are both caused by Clair not supporting Docker versions greater than 1.9.1 (#379)

**Comment by jzelinskie** [comment] 2017-05-24 22:52
This tool is unsupported, I recommend trying out clairctl instead.

**Closed as completed by jzelinskie** 2017-05-24 22:52 UTC
