### ISSUE TITLE
Could not analyze layer: Got response 400 with message. Error Message: Could not find layer

### ISSUE THREAD

**Issue by deejanu** [quay/clair#190] opened 2016-05-26 14:49 UTC
I setup Clair and running Analyze Local Images. It works on some local images without any issues but on others I get:

2016-05-20 09:25:57.938749 I | Saving sha256:f9f99 to local disk (this may take some time)
2016-05-20 09:26:04.761874 I | Retrieving image history
2016-05-20 09:26:04.762038 I | Setting up HTTP server (allowing: 192.168.99.100)
2016-05-20 09:26:04.865555 I | Analyzing 11 layers...
2016-05-20 09:26:04.865594 I | Analyzing cb16cb853eb2c53caf2cd95f3f93ab462953b97ae6f48c935b31e49571b40c8e
2016-05-20 09:26:34.869562 I | Could not analyze layer: Got response 400 with message {"Error":{"Message":"could not find layer"}}

I run:
analyze-local-images -endpoint "http://192.168.99.100:6060" -my-address "192.168.99.1" sha256:f9f99

Any idea what could cause this error and what can be done to fix it?

**Comment by sbehrens** [comment] 2016-05-26 16:02
Sounds similar to what I was seeing, may be related to timeouts with `getsockopt: connection timed out`.  Try to look at your Clair API log, I just opened an issue on this.  

`docker logs clair_container_name | less`

**Comment by deejanu** [comment] 2016-05-26 18:26
Yep, looks like time out:

2016-05-26 18:18:01.264586 W | detectors: could not download layer: Get http://192.168.99.1:9279/cb16cb853eb2c53caf2cd95f3f93ab462953b97ae6f48c935b31e49571b40c8e/layer.tar: dial tcp 192.168.99.1:9279: i/o timeout
2016-05-26 18:18:01.264609 E | worker: layer cb16cb853eb2c53caf2cd95f3f93ab462953b97ae6f48c935b31e49571b40c8e: failed to extract data from http://192.168.99.1:9279/cb16cb853eb2c53caf2cd95f3f93ab462953b97ae6f48c935b31e49571b40c8e/layer.tar: could not find layer
2016-05-26 18:18:01.265661 I | api: 192.168.99.1:65182 "POST /v1/layers" 400 (30.001880511s)

**Comment by schmunk42** [comment] 2017-03-17 14:57
I have the same issue, it looks like claire is trying to get the image layers from `192.168.99.1:9279`.

What should run on this port - on the host - which is serving the images? Could also be related to usage with a VM.

**Comment by Joeyn414** [comment] 2017-03-23 02:59
@Quentin-M and @schmunk42 have you received any feedback on using a docker deployed version of clair and receiving these timeout errors? I have confirmed the api functions with with the postgres db by navigating to http://IPADDRESS/v1/namespaces. This shows all the correct namespaces. When I try to use analyze-local-images as a remote function with clair being specified as the docker clair container (again validated working clair server) and my-endpoint being my virtualbox ubuntu 16.04 vm with a bridged adapter ip address, I continue to get the timeout error. I've pasted in a screen capture of me running the command and the docker logs of the clair container. Any help would be greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/4161494/24230178/07c9cf04-0f54-11e7-94b3-50438b641fe7.png)

**Comment by schmunk42** [comment] 2017-03-23 08:01
I was able to start up a working local stack with `docker-compose` as described in the README.

But I had to run `analyze-local-images` via SSH from my dev-VM on my Mac, otherwise it could not connect to Docker, since it uses `docker.sock`.

**Comment by jmellor** [comment] 2017-03-23 12:26
I think the correct answer is that there is no such thing as what we all want – a remote clair.

After reading through a few snarky responses, I set up my own workaround.  The only way that it apparently works is that the layers all have to be stored on a shared filesystem that you have mounted on you local box.  Realistically, nobody has this for a variety of reasons, so even if you can stomach the security errors that this would introduce, just don’t set it up.

I solved the problem at my site by setting up the Clair host as a Jenkins node, and running a separate analysis job (in the case of freestyle jobs) or a pipeline step that runs on the Clair node, and then pull the image to make it local, inspect it, and then rmi it.

It is not very robust in the event of a crash etc. as it will leave the docker image on the Clair node, but at least it then works the way that the Clair documentation implies that remote image option was supposed to work.

**Comment by jzelinskie** [comment] 2017-05-24 22:25
closing due to age. please remake this issue if it's still relevant. thanks

**Closed as completed by jzelinskie** 2017-05-24 22:25 UTC
Labels: kind/question
