### ISSUE TITLE
Presentation links are broken

### ISSUE THREAD

**Issue by CsatariGergely** [quay/clair#642] opened 2018-10-17 12:43 UTC
### Description of Problem / Feature Request

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are broken.

### Expected Outcome

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are not broken.

### Actual Outcome

The links to the presentations in https://github.com/coreos/clair/blob/master/Documentation/presentations.md are broken.

### Environment

N/A

**Comment by jzelinskie** [comment] 2018-10-17 21:59
duplicate of #560

**Closed as completed by jzelinskie** 2018-10-17 21:59 UTC
Labels: kind/documentation
